import React, { forwardRef } from 'react';
import { Proposal } from '../types';
import { formatCurrency, formatDate } from '../lib/utils';

interface ProposalSummaryProps {
  proposal: Proposal;
  id?: string;
}

export const ProposalSummary = forwardRef<HTMLDivElement, ProposalSummaryProps>(({ proposal, id }, ref) => {
  return (
    <div 
      id={id || "summary-preview"}
      ref={ref}
      className="w-[800px] p-12 bg-white text-slate-900 font-sans"
    >
      <div className="border-b-4 border-indigo-600 pb-6 mb-8">
        <h1 className="text-4xl font-black uppercase tracking-tight text-indigo-600 mb-2">Project Proposal</h1>
        <div className="grid grid-cols-2 gap-4 text-sm font-bold text-slate-500">
          <p>Client Name: {proposal.clientName || 'Valued Client'}</p>
          <p className="text-right">Date: {formatDate(new Date().toISOString())}</p>
          <p>Project Title: {proposal.title}</p>
        </div>
      </div>

      <div className="space-y-8">
        <section>
          <h2 className="text-xl font-black uppercase tracking-widest text-slate-400 mb-3 border-b border-slate-100 pb-1">Executive Summary</h2>
          <p className="text-slate-700 leading-relaxed">{proposal.executiveSummary}</p>
        </section>

        <section>
          <h2 className="text-xl font-black uppercase tracking-widest text-slate-400 mb-3 border-b border-slate-100 pb-1">Scope of Work</h2>
          <ul className="space-y-2">
            {proposal.scopeOfWork.slice(0, 6).map((phase, i) => (
              <li key={i} className="flex items-start gap-2 text-slate-700">
                <span className="text-indigo-600 font-bold">•</span>
                <span>{phase.phase}: {phase.deliverables.slice(0, 2).join(', ')}</span>
              </li>
            ))}
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-black uppercase tracking-widest text-slate-400 mb-3 border-b border-slate-100 pb-1">Timeline</h2>
          <ul className="space-y-2">
            {proposal.timeline.slice(0, 4).map((m, i) => (
              <li key={i} className="flex justify-between text-slate-700">
                <span>{m.milestone}</span>
                <span className="font-bold text-indigo-600">{m.day}</span>
              </li>
            ))}
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-black uppercase tracking-widest text-slate-400 mb-3 border-b border-slate-100 pb-1">Pricing (INR)</h2>
          <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
            <div className="flex justify-between items-center mb-2">
              <span className="text-slate-500 font-bold">Subtotal</span>
              <span className="font-bold">{formatCurrency(proposal.pricingBreakdown.subtotal)}</span>
            </div>
            <div className="flex justify-between items-center pt-2 border-t border-slate-200">
              <span className="text-lg font-black uppercase">Total Amount</span>
              <span className="text-2xl font-black text-indigo-600">{formatCurrency(proposal.pricingBreakdown.total)}</span>
            </div>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-black uppercase tracking-widest text-slate-400 mb-3 border-b border-slate-100 pb-1">Contract Terms</h2>
          <ul className="space-y-2 text-sm text-slate-600 italic">
            <li>• Payment: {proposal.paymentTerms.advance}% advance, {proposal.paymentTerms.delivery}% on completion.</li>
            <li>• Delivery: As per the agreed timeline milestones.</li>
            <li>• Revisions: {proposal.revisionPolicy}</li>
            <li>• Support: 30 days post-launch technical support.</li>
          </ul>
        </section>
      </div>

      <div className="mt-12 pt-8 border-t border-slate-100 flex justify-between items-end">
        <div className="text-xs text-slate-400">
          <p>Generated by ProposalCraft AI</p>
          <p>Professional Freelance Consultant Tool</p>
        </div>
        <div className="w-48 border-t border-slate-900 pt-2 text-center">
          <p className="text-[10px] font-bold uppercase text-slate-400">Authorized Signature</p>
        </div>
      </div>
    </div>
  );
});

ProposalSummary.displayName = 'ProposalSummary';
